keyscan(2)

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -20,6 +20,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
+      - name: keyscan
+        run: ssh-keyscan -H -t rsa -v o.aberger.at || echo "keyscan failed"
+      - name: Setup tmate session (for debugging only)
+        uses: mxschmitt/action-tmate@v3
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'enabled' }}
+
       - name: install ssh key on ubuntu
         uses: caberger/install-ssh-key@v1.0
         with:
@@ -33,12 +39,7 @@ jobs:
           mkdir -p ~/deployment
           echo "this is a test from ubuntu runner" > ~/deployment/test.txt
 
-      - name: keyscan
-        run: ssh-keyscan -H -t rsa -v o.aberger.at || echo "keyscan failed"
 
-      - name: Setup tmate session (for debugging only)
-        uses: mxschmitt/action-tmate@v3
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'enabled' }}
 
       - name: upload artifacts to the server
         run: |
